### ISSUE TITLE
composer.json file?

### ISSUE THREAD

**Issue by JulienMelissas** [Prospress/action-scheduler-high-volume#4]
Would you all be interested in adding a `composer.json` file for those of us who use it to manage dependencies? If so, I'd be happy to submit a PR, but someone would need to publish on packagist.

**Comment by thenbrent** [comment]
Hrm good question. I'm hesitant to add it because I don't want to really encourage use of this plugin as-is.

The plugin was intended to act more as a guide and/or base code to build on rather than a stand-alone plugin that would be installed, then updated with new features in future.

I didn't document this, and should have, but I had an assumption that because there is so little code in here, people would just copy/paste the parts they needed for their site into more persistent places like their theme's `functions.php`, or other places, rather than using this plugin and updating it (overwriting their configuration).

Once you get into the realm of High Volume configuration, it's quite important to test and tweak the actual configuration values, like number of additional runners, number of queues etc.

Having read that, do you think adding `composer.json` is still a good idea? Or should I instead do a better job of advising how to use this plugin's code inline with the above.

**Comment by JulienMelissas** [comment]
Hey there! Your reasoning totally makes sense. I think a little more documentation on the fact that this _should be_ customizable to your needs is probably a great idea. I got that I _could_, but it would be nice to encourage it.

Thanks!
